// src/components/CoordinatorHelper.tsx
import { useState } from 'react'
import type { SignatureResult, CoordinatorBundle } from '../lib/types'

function download(data: string, filename: string) {
  const blob = new Blob([data], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function CoordinatorHelper() {
  const [expanded, setExpanded] = useState(false)
  const [input, setInput] = useState('')
  const [parsed, setParsed] = useState<SignatureResult[] | null>(null)
  const [parseError, setParseError] = useState<string | null>(null)
  const [mismatchWarnings, setMismatchWarnings] = useState<string[]>([])

  const parse = () => {
    setParseError(null)
    setMismatchWarnings([])
    setParsed(null)

    try {
      let sigs: SignatureResult[]
      const trimmed = input.trim()
      if (trimmed.startsWith('[')) {
        sigs = JSON.parse(trimmed)
      } else {
        const objects = trimmed
          .split(/\}\s*\{/)
          .map((s, i, arr) => {
            let obj = s
            if (i > 0) obj = '{' + obj
            if (i < arr.length - 1) obj = obj + '}'
            return obj
          })
        sigs = objects.map((s) => JSON.parse(s))
      }

      if (sigs.length === 0) {
        setParseError('No signatures found')
        return
      }

      for (let i = 0; i < sigs.length; i++) {
        const sig = sigs[i]
        if (!sig.signer || !sig.signature || !sig.payload) {
          setParseError(`Signature #${i + 1} is missing required fields (signer, signature, payload)`)
          return
        }
        if (!sig.signature.r || !sig.signature.s || sig.signature.v === undefined) {
          setParseError(`Signature #${i + 1} is missing r, s, or v`)
          return
        }
      }

      // Check payload consistency
      const ref = sigs[0].payload
      const warnings: string[] = []
      for (let i = 1; i < sigs.length; i++) {
        const p = sigs[i].payload
        if (p.type !== ref.type) warnings.push(`#${i + 1} has different action type`)
        if (p.multisigAddress !== ref.multisigAddress) warnings.push(`#${i + 1} has different multisigAddress`)
        if (p.network !== ref.network) warnings.push(`#${i + 1} has different network`)
        if (JSON.stringify(p.fields) !== JSON.stringify(ref.fields)) warnings.push(`#${i + 1} has different field values`)
      }

      setMismatchWarnings(warnings)
      setParsed(sigs)
    } catch {
      setParseError('Failed to parse JSON. Paste a JSON array of signature objects or individual objects.')
    }
  }

  const exportBundle = () => {
    if (!parsed || parsed.length === 0) return

    const ref = parsed[0].payload
    const innerAction: Record<string, unknown> = { type: ref.type }
    for (const [k, v] of Object.entries(ref.fields)) {
      innerAction[k] = v
    }

    const bundle: CoordinatorBundle = {
      signatures: parsed.map((s) => s.signature),
      inner_action: innerAction,
      multisig_user: ref.multisigAddress,
      network: ref.network,
    }

    const json = JSON.stringify(bundle, null, 2)
    const nonceVal = ref.fields.nonce ?? ref.fields.time ?? 'unknown'
    download(json, `multisig-bundle-${ref.type}-${nonceVal}.json`)
  }

  return (
    <div className="rounded-lg border border-gray-700 bg-gray-900/50">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-gray-300 hover:text-gray-100"
      >
        <span>Coordinator: Collect & Bundle Signatures</span>
        <span className="text-gray-500">{expanded ? '[-]' : '[+]'}</span>
      </button>

      {expanded && (
        <div className="border-t border-gray-700 p-4 space-y-4">
          <p className="text-xs text-gray-400">
            Paste signature JSON blobs from all signers. The tool will validate that all payloads
            match and export a bundle for the Python submit flow.
          </p>

          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={'Paste signature JSON objects here...\n[\n  { "signer": "0x...", "signature": {...}, "payload": {...} },\n  { "signer": "0x...", "signature": {...}, "payload": {...} }\n]'}
            className="w-full h-40 rounded-md border border-gray-700 bg-gray-900 px-3 py-2 font-mono text-xs text-gray-300 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500/50 resize-y"
          />

          <div className="flex gap-2">
            <button
              onClick={parse}
              disabled={!input.trim()}
              className="rounded-md border border-gray-600 bg-gray-800 px-4 py-2 text-sm text-gray-200 hover:bg-gray-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Validate & Parse
            </button>
            {parsed && (
              <button
                onClick={exportBundle}
                disabled={mismatchWarnings.length > 0}
                className="rounded-md border border-blue-600 bg-blue-700 px-4 py-2 text-sm text-white hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Export Bundle (.json)
              </button>
            )}
          </div>

          {parseError && (
            <div className="rounded-md border border-red-800 bg-red-950/50 px-3 py-2 text-xs text-red-300">
              {parseError}
            </div>
          )}

          {mismatchWarnings.length > 0 && (
            <div className="rounded-md border border-red-800 bg-red-950/50 px-3 py-2 text-xs text-red-300">
              <div className="font-medium mb-1">Payload mismatch detected — signatures are incompatible:</div>
              <ul className="list-disc pl-4">
                {mismatchWarnings.map((w, i) => (
                  <li key={i}>{w}</li>
                ))}
              </ul>
            </div>
          )}

          {parsed && mismatchWarnings.length === 0 && (
            <div className="rounded-md border border-green-800 bg-green-950/50 px-3 py-2 text-xs text-green-300">
              {parsed.length} signature(s) validated. All payloads match. Ready to export bundle.
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// src/lib/components/CoordinatorHelper.svelte
<script lang="ts">
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Textarea } from '$lib/components/ui/textarea/index.js';
	import { Alert, AlertDescription } from '$lib/components/ui/alert/index.js';
	import type { SignatureResult, CoordinatorBundle } from '$lib/types.js';
	import { getActionDef } from '$lib/eip712.js';
	import { executeBundle } from '$lib/execute.js';
	import { getWallet } from '$lib/wallet.svelte.js';

	const wallet = getWallet();

	let expanded = $state(false);
	let input = $state('');
	let parsed = $state<SignatureResult[] | null>(null);
	let parseError = $state<string | null>(null);
	let mismatchWarnings = $state<string[]>([]);
	let executing = $state(false);
	let executeResult = $state<{ success: boolean; response: unknown; requestBody: unknown } | null>(null);
	let executeError = $state<string | null>(null);

	function toggle() {
		expanded = !expanded;
	}

	function validateAndParse() {
		parseError = null;
		parsed = null;
		mismatchWarnings = [];

		if (!input.trim()) {
			parseError = 'Paste signature JSON(s) above.';
			return;
		}

		let sigs: SignatureResult[];
		try {
			const raw = JSON.parse(input.trim());
			if (Array.isArray(raw)) {
				sigs = raw as SignatureResult[];
			} else if (typeof raw === 'object' && raw !== null && raw.signer) {
				sigs = [raw as SignatureResult];
			} else {
				parseError = 'Expected a signature object or array of signature objects.';
				return;
			}
		} catch {
			// Try parsing multiple JSON objects separated by newlines/commas
			try {
				const wrapped = '[' + input.trim().replace(/\}\s*\{/g, '},{') + ']';
				sigs = JSON.parse(wrapped) as SignatureResult[];
			} catch {
				parseError = 'Invalid JSON. Paste a signature object or array.';
				return;
			}
		}

		if (sigs.length === 0) {
			parseError = 'No signatures found.';
			return;
		}

		// Validate all have required fields
		for (let i = 0; i < sigs.length; i++) {
			const sig = sigs[i];
			if (!sig.signer || !sig.signature || !sig.payload) {
				parseError = `Signature #${i + 1} is missing required fields (signer, signature, payload).`;
				return;
			}
		}

		// Check consistency across all signatures
		const ref = sigs[0].payload;
		const warnings: string[] = [];
		for (let i = 1; i < sigs.length; i++) {
			const p = sigs[i].payload;
			if (p.type !== ref.type) warnings.push(`Sig #${i + 1}: action type "${p.type}" differs from #1 "${ref.type}"`);
			if (p.multisigAddress !== ref.multisigAddress) warnings.push(`Sig #${i + 1}: multisig address differs`);
			if (p.network !== ref.network) warnings.push(`Sig #${i + 1}: network "${p.network}" differs from #1 "${ref.network}"`);
			// Check fields
			for (const [key, val] of Object.entries(ref.fields)) {
				if (String(p.fields[key]) !== String(val)) {
					warnings.push(`Sig #${i + 1}: field "${key}" value differs`);
				}
			}
		}

		mismatchWarnings = warnings;
		parsed = sigs;
	}

	function buildBundle(): CoordinatorBundle {
		if (!parsed || parsed.length === 0) throw new Error('No signatures parsed');
		const ref = parsed[0].payload;
		const actionDef = getActionDef(ref.type);
		let innerAction: Record<string, unknown>;
		if (actionDef.buildAction) {
			innerAction = actionDef.buildAction(ref.fields as Record<string, string>);
		} else {
			// Build inner action matching Python SDK field order.
			// The inner action in the multiSig payload must NOT include
			// signatureChainId or hyperliquidChain — the Python SDK adds
			// those only to the EIP-712 signing copy, not the original action
			// passed to multi_sig().
			innerAction = { type: ref.type };
			for (const field of actionDef.fields) {
				const raw = ref.fields[field.name] as string ?? '';
				switch (field.eip712Type) {
					case 'uint64':
						innerAction[field.name] = parseInt(raw, 10);
						break;
					case 'bool':
						innerAction[field.name] = raw === 'true';
						break;
					default:
						innerAction[field.name] = raw;
				}
			}
		}

		return {
			signatures: parsed.map((s) => s.signature),
			inner_action: innerAction,
			multisig_user: ref.multisigAddress,
			network: ref.network,
		};
	}

	function exportBundle() {
		if (!parsed || parsed.length === 0) return;
		const bundle = buildBundle();
		const json = JSON.stringify(bundle, null, 2);
		const blob = new Blob([json], { type: 'application/json' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `bundle-${parsed[0].payload.type}-${Date.now()}.json`;
		a.click();
		URL.revokeObjectURL(url);
	}

	async function execute() {
		if (!parsed || parsed.length === 0) return;
		if (!wallet.provider || !wallet.address) {
			executeError = 'Connect your wallet first.';
			return;
		}
		executing = true;
		executeError = null;
		executeResult = null;
		try {
			const bundle = buildBundle();
			const vaultAddress = parsed[0].payload.vaultAddress || null;
			const result = await executeBundle(wallet.provider, wallet.address, bundle, vaultAddress);
			executeResult = result;
		} catch (err) {
			executeError = err instanceof Error ? err.message : String(err);
		} finally {
			executing = false;
		}
	}
</script>

<Card>
	<CardHeader>
		<button
			class="flex w-full items-center justify-between text-left"
			onclick={toggle}
		>
			<CardTitle class="text-sm">Coordinator: Collect & Bundle Signatures</CardTitle>
			<span class="text-muted-foreground text-xs">{expanded ? '[-]' : '[+]'}</span>
		</button>
	</CardHeader>

	{#if expanded}
		<CardContent class="space-y-4">
			<div class="space-y-2">
				<p class="text-muted-foreground text-xs">
					Paste signature JSONs below (array or individual objects).
				</p>
				<Textarea
					placeholder={'[{"signer":"0x...","signature":{...},"payload":{...}}, ...]'}
					bind:value={input}
					rows={6}
					class="font-mono text-xs"
				/>
			</div>

			<Button variant="outline" size="sm" onclick={validateAndParse}>
				Validate & Parse
			</Button>

			{#if parseError}
				<Alert variant="destructive">
					<AlertDescription>{parseError}</AlertDescription>
				</Alert>
			{/if}

			{#if mismatchWarnings.length > 0}
				<Alert class="border-yellow-500/50 bg-yellow-50 dark:bg-yellow-950/50">
					<AlertDescription>
						<ul class="list-disc space-y-1 pl-4 text-xs">
							{#each mismatchWarnings as warning, i (i)}
								<li>{warning}</li>
							{/each}
						</ul>
					</AlertDescription>
				</Alert>
			{/if}

			{#if parsed}
				<div class="space-y-2">
					<p class="text-sm">
						Parsed <strong>{parsed.length}</strong> signature{parsed.length !== 1 ? 's' : ''} from
						{#each parsed as sig, i (sig.signer)}
							<span class="font-mono text-xs">{sig.signer.slice(0, 8)}...</span>{i < parsed.length - 1 ? ', ' : ''}
						{/each}
					</p>
					<div class="flex gap-2">
						<Button variant="outline" size="sm" onclick={exportBundle}>
							Export Bundle
						</Button>
						<Button
							variant="default"
							size="sm"
							onclick={execute}
							disabled={executing || !wallet.connected}
						>
							{executing ? 'Executing…' : 'Execute'}
						</Button>
					</div>
				</div>
			{/if}

			{#if executeError}
				<Alert variant="destructive">
					<AlertDescription>{executeError}</AlertDescription>
				</Alert>
			{/if}

			{#if executeResult}
				<Alert class={executeResult.success ? 'border-green-500/50 bg-green-50 dark:bg-green-950/50' : 'border-red-500/50 bg-red-50 dark:bg-red-950/50'}>
					<AlertDescription>
						{#if executeResult.success}
							Transaction submitted successfully.
						{:else}
							<div class="space-y-2">
								<div>Submission failed: {JSON.stringify(executeResult.response)}</div>
								<div class="text-xs font-medium">Request body sent:</div>
								<pre class="overflow-auto text-xs">{JSON.stringify(executeResult.requestBody, null, 2)}</pre>
							</div>
						{/if}
					</AlertDescription>
				</Alert>
			{/if}
		</CardContent>
	{/if}
</Card>
