// src/components/PayloadForm.tsx
import { validateField } from '../lib/validation'
import { getAllActions, getActionDef } from '../lib/eip712'
import type { ActionType, FormValues, Network } from '../lib/types'

interface Props {
  values: FormValues
  onChange: (values: FormValues) => void
  errors: Record<string, string | null>
  onErrorsChange: (errors: Record<string, string | null>) => void
}

function FieldLabel({ label, help }: { label: string; help?: string }) {
  return (
    <div>
      <label className="block text-xs text-gray-400 mb-1">{label}</label>
      {help && <div className="text-xs text-gray-600 mb-1">{help}</div>}
    </div>
  )
}

function InputField({
  label,
  value,
  onChange,
  error,
  placeholder,
  mono = false,
  help,
}: {
  label: string
  value: string
  onChange: (v: string) => void
  error?: string | null
  placeholder?: string
  mono?: boolean
  help?: string
}) {
  return (
    <div>
      <FieldLabel label={label} help={help} />
      <input
        type="text"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className={`w-full rounded-md border bg-gray-900 px-3 py-2 text-sm ${
          mono ? 'font-mono' : ''
        } ${
          error
            ? 'border-red-600 text-red-300 focus:border-red-500'
            : 'border-gray-700 text-gray-100 focus:border-blue-500'
        } focus:outline-none focus:ring-1 focus:ring-blue-500/50`}
      />
      {error && <div className="mt-1 text-xs text-red-400">{error}</div>}
    </div>
  )
}

function JsonField({
  label,
  value,
  onChange,
  error,
  placeholder,
  help,
}: {
  label: string
  value: string
  onChange: (v: string) => void
  error?: string | null
  placeholder?: string
  help?: string
}) {
  return (
    <div>
      <FieldLabel label={label} help={help} />
      <textarea
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        rows={6}
        className={`w-full rounded-md border bg-gray-900 px-3 py-2 font-mono text-xs ${
          error
            ? 'border-red-600 text-red-300 focus:border-red-500'
            : 'border-gray-700 text-gray-100 focus:border-blue-500'
        } focus:outline-none focus:ring-1 focus:ring-blue-500/50 resize-y`}
      />
      {error && <div className="mt-1 text-xs text-red-400">{error}</div>}
    </div>
  )
}

function BoolField({
  label,
  value,
  onChange,
  help,
}: {
  label: string
  value: string
  onChange: (v: string) => void
  help?: string
}) {
  return (
    <div>
      <FieldLabel label={label} help={help} />
      <div className="flex gap-2">
        {['true', 'false'].map((opt) => (
          <button
            key={opt}
            onClick={() => onChange(opt)}
            className={`flex-1 rounded-md border px-3 py-2 text-sm font-medium transition-colors ${
              value === opt
                ? 'border-blue-600 bg-blue-950 text-blue-300'
                : 'border-gray-700 bg-gray-900 text-gray-500 hover:border-gray-600'
            }`}
          >
            {opt === 'true' ? 'Yes' : 'No'}
          </button>
        ))}
      </div>
    </div>
  )
}

function NonceField({
  label,
  value,
  onChange,
  error,
}: {
  label: string
  value: string
  onChange: (v: string) => void
  error?: string | null
}) {
  return (
    <div>
      <label className="block text-xs text-gray-400 mb-1">{label}</label>
      <div className="flex gap-2">
        <input
          type="text"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder="Timestamp in ms"
          className={`flex-1 rounded-md border bg-gray-900 px-3 py-2 font-mono text-sm ${
            error
              ? 'border-red-600 text-red-300'
              : 'border-gray-700 text-gray-100 focus:border-blue-500'
          } focus:outline-none focus:ring-1 focus:ring-blue-500/50`}
        />
        <button
          onClick={() => onChange(Date.now().toString())}
          className="rounded-md border border-gray-700 bg-gray-800 px-3 py-2 text-xs text-gray-300 hover:bg-gray-700 hover:text-gray-100 whitespace-nowrap"
        >
          Now (ms)
        </button>
      </div>
      {error && <div className="mt-1 text-xs text-red-400">{error}</div>}
    </div>
  )
}

export function PayloadForm({ values, onChange, errors, onErrorsChange }: Props) {
  const allActions = getAllActions()
  const actionDef = getActionDef(values.actionType)

  const updateActionType = (type: ActionType) => {
    const newDef = getActionDef(type)
    const newFields: Record<string, string> = {}
    for (const f of newDef.fields) {
      newFields[f.name] = f.eip712Type === 'bool' ? 'false' : ''
    }
    onChange({
      ...values,
      actionType: type,
      fields: newFields,
    })
    onErrorsChange({ multisigAddress: errors.multisigAddress })
  }

  const updateField = (fieldName: string, value: string) => {
    const newFields = { ...values.fields, [fieldName]: value }
    onChange({ ...values, fields: newFields })

    const fieldDef = actionDef.fields.find((f) => f.name === fieldName)
    if (fieldDef) {
      const error = value ? validateField(value, fieldDef.eip712Type, fieldDef.required) : null
      onErrorsChange({ ...errors, [fieldName]: error })
    }
  }

  const updateMultisig = (value: string) => {
    onChange({ ...values, multisigAddress: value })
    onErrorsChange({
      ...errors,
      multisigAddress: value ? validateField(value, 'address', true) : null,
    })
  }

  // Group actions by signing mode for the dropdown
  const userSignedActions = allActions.filter((a) => a.signingMode === 'user-signed')
  const l1Actions = allActions.filter((a) => a.signingMode === 'l1')

  return (
    <div className="space-y-4">
      {/* Action type dropdown */}
      <div>
        <label className="block text-xs text-gray-400 mb-1">Action Type</label>
        <select
          value={values.actionType}
          onChange={(e) => updateActionType(e.target.value as ActionType)}
          className="w-full rounded-md border border-gray-700 bg-gray-900 px-3 py-2 text-sm text-gray-100 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500/50"
        >
          <optgroup label="User-Signed Actions (EIP-712)">
            {userSignedActions.map((a) => (
              <option key={a.type} value={a.type}>{a.label}</option>
            ))}
          </optgroup>
          <optgroup label="L1 Actions (Phantom Agent)">
            {l1Actions.map((a) => (
              <option key={a.type} value={a.type}>{a.label}</option>
            ))}
          </optgroup>
        </select>
        <div className="mt-1 flex items-center gap-2">
          <span className={`inline-block rounded px-1.5 py-0.5 text-xs font-medium ${
            actionDef.signingMode === 'user-signed'
              ? 'bg-blue-950 text-blue-300 border border-blue-800'
              : 'bg-purple-950 text-purple-300 border border-purple-800'
          }`}>
            {actionDef.signingMode === 'user-signed' ? 'EIP-712' : 'L1 Phantom Agent'}
          </span>
          <span className="text-xs text-gray-500">{actionDef.description}</span>
        </div>
      </div>

      {/* Multisig address — common to all actions */}
      <InputField
        label="Multisig Address (payloadMultiSigUser)"
        value={values.multisigAddress}
        onChange={updateMultisig}
        error={errors.multisigAddress}
        placeholder="0x..."
        mono
      />

      {/* Action-specific fields */}
      {actionDef.fields.map((field) => {
        if (field.eip712Type === 'bool') {
          return (
            <BoolField
              key={field.name}
              label={field.label}
              value={values.fields[field.name] ?? 'false'}
              onChange={(v) => updateField(field.name, v)}
              help={field.help}
            />
          )
        }
        if (field.eip712Type === 'uint64') {
          return (
            <NonceField
              key={field.name}
              label={field.label}
              value={values.fields[field.name] ?? ''}
              onChange={(v) => updateField(field.name, v)}
              error={errors[field.name]}
            />
          )
        }
        if (field.eip712Type === 'json') {
          return (
            <JsonField
              key={field.name}
              label={field.label}
              value={values.fields[field.name] ?? ''}
              onChange={(v) => updateField(field.name, v)}
              error={errors[field.name]}
              placeholder={field.placeholder}
              help={field.help}
            />
          )
        }
        return (
          <InputField
            key={field.name}
            label={field.label}
            value={values.fields[field.name] ?? ''}
            onChange={(v) => updateField(field.name, v)}
            error={errors[field.name]}
            placeholder={field.placeholder}
            mono={field.mono}
            help={field.help}
          />
        )
      })}

      {/* Network toggle */}
      <div>
        <label className="block text-xs text-gray-400 mb-1">Network</label>
        <div className="flex gap-2">
          {(['Mainnet', 'Testnet'] as Network[]).map((net) => (
            <button
              key={net}
              onClick={() => onChange({ ...values, network: net })}
              className={`flex-1 rounded-md border px-3 py-2 text-sm font-medium transition-colors ${
                values.network === net
                  ? net === 'Mainnet'
                    ? 'border-green-600 bg-green-950 text-green-300'
                    : 'border-yellow-600 bg-yellow-950 text-yellow-300'
                  : 'border-gray-700 bg-gray-900 text-gray-500 hover:border-gray-600'
              }`}
            >
              {net}
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}

// src/lib/components/PayloadForm.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label/index.js';
	import { Textarea } from '$lib/components/ui/textarea/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import {
		Select,
		SelectContent,
		SelectGroup,
		SelectGroupHeading,
		SelectItem,
		SelectTrigger,
	} from '$lib/components/ui/select/index.js';
	import { ACTION_REGISTRY, getAllActions, getActionDef } from '$lib/eip712.js';
	import { validateField, validateAddress } from '$lib/validation.js';
	import type { FormValues, ActionType, FieldDef } from '$lib/types.js';

	interface Props {
		values: FormValues;
		errors: Record<string, string | null>;
		locked?: boolean;
	}

	let { values = $bindable(), errors = $bindable(), locked = false }: Props = $props();

	const allActions = getAllActions();
	const userSignedActions = $derived(allActions.filter((a) => a.signingMode === 'user-signed'));
	const l1Actions = $derived(allActions.filter((a) => a.signingMode === 'l1'));
	const actionDef = $derived(getActionDef(values.actionType));

	// Track select value for shadcn Select (uses string value)
	let selectValue = $state(values.actionType as string);

	function updateActionType(type: string) {
		const actionType = type as ActionType;
		const def = getActionDef(actionType);
		const newFields: Record<string, string> = {};
		for (const field of def.fields) {
			newFields[field.name] = '';
		}
		values = {
			...values,
			actionType,
			fields: newFields,
		};
		errors = {};
		selectValue = type;
	}

	function updateField(name: string, value: string) {
		values = {
			...values,
			fields: { ...values.fields, [name]: value },
		};
		// Find the field def and validate
		const fieldDef = actionDef.fields.find((f) => f.name === name);
		if (fieldDef) {
			errors = { ...errors, [name]: validateField(value, fieldDef.eip712Type, fieldDef.required) };
		}
	}

	function updateMultisigAddress(value: string) {
		values = { ...values, multisigAddress: value };
		errors = { ...errors, multisigAddress: validateAddress(value) };
	}

	function fillNow(fieldName: string) {
		updateField(fieldName, Date.now().toString());
	}

	function setNetwork(network: 'Mainnet' | 'Testnet') {
		values = { ...values, network };
	}

	function setBoolField(fieldName: string, val: boolean) {
		updateField(fieldName, val.toString());
	}
</script>

<div class="space-y-5">
	<!-- Action Type Selector -->
	<div class="space-y-2">
		<Label>Action Type</Label>
		<Select
			type="single"
			value={selectValue}
			onValueChange={(v) => { if (v) updateActionType(v); }}
			disabled={locked}
		>
			<SelectTrigger class="w-full">
				{actionDef.label}
			</SelectTrigger>
			<SelectContent>
				<SelectGroup>
					<SelectGroupHeading>User-Signed (EIP-712)</SelectGroupHeading>
					{#each userSignedActions as action (action.type)}
						<SelectItem value={action.type} label={action.label} />
					{/each}
				</SelectGroup>
				<SelectGroup>
					<SelectGroupHeading>L1 Actions (Phantom Agent)</SelectGroupHeading>
					{#each l1Actions as action (action.type)}
						<SelectItem value={action.type} label={action.label} />
					{/each}
				</SelectGroup>
			</SelectContent>
		</Select>
		<p class="text-muted-foreground text-xs">{actionDef.description}</p>
	</div>

	<!-- Signing Mode Badge + Network Toggle -->
	<div class="flex items-center justify-between">
		<Badge variant={actionDef.signingMode === 'l1' ? 'secondary' : 'default'}>
			{actionDef.signingMode === 'l1' ? 'L1 Phantom Agent' : 'EIP-712 Direct'}
		</Badge>
		<div class="flex gap-1">
			<Button
				variant={values.network === 'Mainnet' ? 'default' : 'outline'}
				size="sm"
				disabled={locked}
				onclick={() => setNetwork('Mainnet')}
			>
				Mainnet
			</Button>
			<Button
				variant={values.network === 'Testnet' ? 'default' : 'outline'}
				size="sm"
				disabled={locked}
				onclick={() => setNetwork('Testnet')}
			>
				Testnet
			</Button>
		</div>
	</div>

	<!-- Multisig Address -->
	<div class="space-y-2">
		<Label for="multisigAddress">Multisig Address</Label>
		<Input
			id="multisigAddress"
			placeholder="0x..."
			value={values.multisigAddress}
			oninput={(e) => updateMultisigAddress(e.currentTarget.value)}
			disabled={locked}
			class="font-mono text-xs"
		/>
		{#if errors.multisigAddress}
			<p class="text-destructive text-xs">{errors.multisigAddress}</p>
		{/if}
	</div>

	<!-- Dynamic Fields -->
	{#each actionDef.fields as field (field.name)}
		<div class="space-y-2">
			<Label for={field.name}>
				{field.label}
				{#if field.required}
					<span class="text-destructive">*</span>
				{/if}
			</Label>

			{#if field.eip712Type === 'bool'}
				<!-- Boolean toggle buttons -->
				<div class="flex gap-1">
					<Button
						variant={values.fields[field.name] === 'true' ? 'default' : 'outline'}
						size="sm"
						disabled={locked}
						onclick={() => setBoolField(field.name, true)}
					>
						Yes
					</Button>
					<Button
						variant={values.fields[field.name] === 'false' ? 'default' : 'outline'}
						size="sm"
						disabled={locked}
						onclick={() => setBoolField(field.name, false)}
					>
						No
					</Button>
				</div>
			{:else if field.eip712Type === 'json'}
				<!-- JSON textarea -->
				<Textarea
					id={field.name}
					placeholder={field.placeholder}
					value={values.fields[field.name] ?? ''}
					oninput={(e) => updateField(field.name, e.currentTarget.value)}
					disabled={locked}
					class="font-mono text-xs"
					rows={4}
				/>
			{:else if field.eip712Type === 'uint64'}
				<!-- Nonce/timestamp with "Now" button -->
				<div class="flex gap-2">
					<Input
						id={field.name}
						placeholder={field.placeholder}
						value={values.fields[field.name] ?? ''}
						oninput={(e) => updateField(field.name, e.currentTarget.value)}
						disabled={locked}
						class={field.mono ? 'font-mono text-xs' : ''}
					/>
					<Button
						variant="outline"
						size="sm"
						disabled={locked}
						onclick={() => fillNow(field.name)}
					>
						Now (ms)
					</Button>
				</div>
			{:else}
				<!-- Standard text input -->
				<Input
					id={field.name}
					placeholder={field.placeholder}
					value={values.fields[field.name] ?? ''}
					oninput={(e) => updateField(field.name, e.currentTarget.value)}
					disabled={locked}
					class={field.mono ? 'font-mono text-xs' : ''}
				/>
			{/if}

			{#if field.help}
				<p class="text-muted-foreground text-xs">{field.help}</p>
			{/if}
			{#if errors[field.name]}
				<p class="text-destructive text-xs">{errors[field.name]}</p>
			{/if}
		</div>
	{/each}
</div>
